# -*- coding: utf-8 -*-
"""Chicago.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mK0rENinO6zqxP7ldpdtzfAXTSDTkLzb
"""

# EDA for dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
from sklearn.datasets import load_wine

plt.style.use("ggplot")
rcParams['figure.figsize'] = (12, 6)

df14 = pd.read_csv("Chicago_Crimes_2001_to_2004.csv", delimiter=',', low_memory=False, on_bad_lines='skip')
df57 = pd.read_csv("Chicago_Crimes_2005_to_2007.csv", delimiter=',', low_memory=False, on_bad_lines='skip')
df811 = pd.read_csv("Chicago_Crimes_2008_to_2011.csv", delimiter=',', low_memory=False, on_bad_lines='skip')
df1217 = pd.read_csv("Chicago_Crimes_2012_to_2017.csv", delimiter=',', low_memory=False, on_bad_lines='skip')

df.head()

df.info()

df.duplicated().sum()

df14.drop_duplicates()
df57.drop_duplicates()
df811.drop_duplicates()
df1217.drop_duplicates()

df14.rename(columns={"Primary Type": "crime_type"}, inplace=True)
df57.rename(columns={"Primary Type": "crime_type"}, inplace=True)
df811.rename(columns={"Primary Type": "crime_type"}, inplace=True)
df1217.rename(columns={"Primary Type": "crime_type"}, inplace=True)

df14.crime_type.value_counts().plot(kind="bar")
plt.title("Chicago crimes from 2001-2004")
plt.xlabel("Crime")
plt.xticks(rotation=0)
plt.ylabel("Count")
plt.show()

df57.crime_type.value_counts().plot(kind="bar")
plt.title("Chicago crimes from 2001-2004")
plt.xlabel("Crime")
plt.xticks(rotation=0)
plt.ylabel("Count")
plt.show()

df811.crime_type.value_counts().plot(kind="bar")
plt.title("Chicago crimes from 2001-2004")
plt.xlabel("Crime")
plt.xticks(rotation=0)
plt.ylabel("Count")
plt.show()

df1217.crime_type.value_counts().plot(kind="bar")
plt.title("Chicago crimes from 2001-2004")
plt.xlabel("Crime")
plt.xticks(rotation=0)
plt.ylabel("Count")
plt.show()

df14.crime_type.describe()
df57.crime_type.describe()
df811.crime_type.describe()
df1217.crime_type.describe()

df.crime_type.hist()

df14 = df14.dropna()
df57 = df57.dropna()
df811 = df811.dropna()
df1217 = df1217.dropna()

# local Operating System
!pip install geopandas geodatasets
import os

# Visualisation

import geopandas
from geopandas import GeoDataFrame

# Dataframe
import pandas as pd
from shapely.geometry import Point, Polygon

import geodatasets
chicago = geopandas.read_file(geodatasets.get_path("geoda.chicago_commpop"))

chicago.plot()

chicago.plot(column="POP2010",figsize=(10, 6))
#chicago.plot(column='POP2010', legend=True)

df.head(1)

df = df.drop('Updated On',axis =1)
df.head()

location = [Point(xy) for xy in zip(df['Latitude'], df['Longitude'])]

gdf14 = GeoDataFrame(df14, geometry=location)
ax = chicago.plot()
gdf14.plot(ax.plot(figsize=(10, 6)), marker='+', color='red', markersize=2);

gdf57 = GeoDataFrame(df57, geometry=location)
ax = chicago.plot()
gdf57.plot(ax.plot(figsize=(10, 6)), marker='+', color='red', markersize=2);

gdf811 = GeoDataFrame(df811, geometry=location)
ax = chicago.plot()
gdf811.plot(ax.plot(figsize=(10, 6)), marker='+', color='red', markersize=2);

gdf1217 = GeoDataFrame(df1217, geometry=location)
ax = chicago.plot()
gdf1217.plot(ax.plot(figsize=(10, 6)), marker='+', color='red', markersize=2);



base = chicago.plot(color='white', edgecolor='black')

gdf.plot(base.plot(figsize=(10, 6)), marker='+', color='red', markersize=2)

